### ISSUE TITLE
flutter1.7.8报错  'Null Function(StringBuffer)'

### ISSUE THREAD

**Issue by zengde** [zengde/reader_flutter#1]
来自：flutter_cached_network_image库0.7.0
参考：https://github.com/renefloor/flutter_cached_network_image/issues/171
修改： Dart Packages > cached_network_image-0.7.0 > src > cached_network_image_provider.dart  46行
```dart
@override
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
    return new MultiFrameImageStreamCompleter(
        codec: _loadAsync(key),
        scale: key.scale,
    );
  }
```

**Comment by lycstar** [comment]
可能是Flutter版本不对

**Comment by zengde** [comment]
cached_network_image库已更新修复
